name: CI Build Frontend

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Clean node_modules and package-lock.json
        run: | 
          rm -rf node_modules package-lock.json

      - name: Install dependencies from mirror
        run: npm install --registry=https://registry.npmmirror.com
        
      - name: Build Angular
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/frontend

      - name: log completion
        run: echo "operacion exitosa"





