name: CI Build Frontend

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build Angular
        working-directory: frontend
        run: ng build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: frontend/dist

      - name: log completion
        run: echo "operacion exitosa"





