name: Build on Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and Build
        working-directory: frontend
        run: |
          npm install
          npm run build --if-present

      - name: Zip build output
        run: zip -r release.zip frontend/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: release.zip
