name: Build on Pull Request to Develop

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build Angular app
        working-directory: frontend
        run: |
          npm install
          npm run build --if-present

      - name: Zip Angular build output
        working-directory: frontend/dist
        run: |
          zip -r ../../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: release.zip
