name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Desplegar a Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-service-frontend  # <-- reemplazá con el nombre real de tu App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROFILE_FRONTEND }}
          package: dist/
